### ISSUE TITLE
Last played date not working

### ISSUE THREAD

**Issue by moon827** [Derpthemeus/ChampionMasteryLookup#18] opened 2018-11-19 20:20 UTC
Its not showing my last played, check my sona for example compared to my op.gg

https://championmasterylookup.derpthemeus.com/summoner?summoner=moon827&region=NA

http://na.op.gg/summoner/userName=moon827

**Comment by Derpthemeus** [comment] 2018-11-19 20:37
This is caused by a known issue with Riot's API. The team that owns the champion mastery service has been made aware of it, but there is no estimate as to when it will be fixed.

**Comment by Derpthemeus** [comment] 2019-08-12 21:35
This should now be resolved https://github.com/RiotGames/developer-relations/issues/15

**Closed by Derpthemeus** 2019-08-12 21:35 UTC
